name: 持续集成

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Java 环境
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 缓存 Maven 依赖
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: 编译项目
      run: mvn clean compile
      
    - name: 运行测试
      run: mvn test
      continue-on-error: true  # 允许测试失败，因为可能没有测试
      
    - name: 打包项目
      run: mvn package -DskipTests
      
    - name: 验证构建产物
      run: |
        echo "验证构建产物..."
        ls -la target/
        if [ ! -f target/RemoveExtraBlankLines-*.jar ]; then
          echo "❌ JAR 文件未生成"
          exit 1
        fi
        echo "✅ 构建验证成功"
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: burp-plugin-jar
        path: target/RemoveExtraBlankLines-*.jar
        retention-days: 7 